kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: tigera-prometheus
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: nigel@tigera.io
        send_resolved: false
        from: no-reply@alerts.com
        smarthost: smtp.gmail.com:25
        require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/XYZXYZXYZXYZXYZYXYZYXYZYXYZXYZ
        channel: '#alertmanager'
