apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default.deny-from-other-namespaces
  namespace: default
spec:
  tier: default
  order: 1000
  selector: all()
  serviceAccountSelector: ''
  types:
    - Ingress
